services:
  postgres:
    container_name: postgres_sb
    image: postgres
    environment:
      POSTGRES_USER: pcodes
      POSTGRES_PASSWORD: pcodes
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - skillbridge-net
    restart: unless-stopped

  mongodb:
    image: mongo
    container_name: mongo_sb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=pcodes
      - MONGO_INITDB_ROOT_PASSWORD=pcodes
    volumes:
      - mongo:/data/db
    ports:
      - "27017:27017"
    networks:
      - skillbridge-net
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    container_name: mongo_express_sb
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=pcodes
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pcodes
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH=false
    depends_on:
      - mongodb
    networks:
      - skillbridge-net
    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper_sb
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - skillbridge-net
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka_sb
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    ports:
      - "9092:9092"
    networks:
      - skillbridge-net
    restart: unless-stopped

  maildev:
    container_name: mail_dev_sb
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - skillbridge-net
    restart: unless-stopped

  redis:
    image: redis
    container_name: redis_sb
    command: redis-server --appendonly yes --requirepass skillbridge_redis_pass
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - skillbridge-net
    restart: unless-stopped

networks:
  skillbridge-net:
    driver: bridge

volumes:
  postgres:
  mongo:
  redis_data:
  keycloak:
